[[libsigcpp]]
arch = "aarch64"
git-tree-sha1 = "3557afbb6dca55cf3c8d9967ced66ba718a3d062"
os = "macos"

    [[libsigcpp.download]]
    sha256 = "647bc00a322e21b11f5edde0183958e0d6c98443cdd1260af5be703f58aa4c83"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.aarch64-apple-darwin.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdb391b18b9362a62d15a743715a0b38ecc354e4"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "1c792c510ce0f3dd92dd54e0fb079e7dd5931cde1258896da3e3a080315cef48"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b44bf93e72a21e7db183312ff446e4d7a4783c5b"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "6104f1a5780c82476f8ab1285449abf933223d9f52ce533d98f992fe9b789688"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00a80ba28ab84249e947e374ee566018b4f824c9"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "804c72f9e3f47a89bec10a8223156404b1800e792d24d0c27beaa565d8b4638c"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7661a01e3a4252b1980810f16e7a54b546d12316"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "732b05378cf9c0e9caa1679a89d6aaebe48e6a6a8d3e38372c0cd6aa40e77d3d"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "099a90af652d04f1e97d8c1d8df9e6e0a6299972"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "c595e28fabac598204f67acb9615c683da9a09ae46c677472cb14bfcfe8e4516"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "871993e3b4e0e7710a509323cf4dcc37a402822a"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "2b986e025c7922ff7d9a594e52b4c951ff6d98d39e0e72ac44b7142a576dc979"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f08459d0e7f46c62690f7473191ab58cd9b1b26b"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "ab065f85522e4cc211794a4836afca0481c0d3a748b245a6d336f2c9f286b015"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ca18f67d810595d02bdefc3c25d07e640cf7884"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "686be94c62c01c70859fbf74ced0dc11d3687599d726fb6c6fa89ab4a4798fb2"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc33f445b8d677e7c006409323733b90407c222b"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "0c0d4f3e2d460f768c8ee9a4af10ff77ed55fb9e6376deb7e851a93c579feb3d"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "693c52ddce11f763cc2d751ef93aff913293bfab"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "2d35f65d07fafdf3026e1b42eb5d1a4a734e168dde408f1828dd18687492fdf7"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b349768c40c50144485c0f303fe737cbe652470b"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "1afc0b2a9c160fed2c6b11d1d9b7950786fa26c88c5319fc499f32ec7c7a4217"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79f4200576c3fd8797e8c02ae2c2d51b306cec6b"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "1053aaca6d8dda087b25a106c23b9e3f40a4dbe04f9cd99411f98306fcec4114"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "593bd3df05299614975af0d650f3eb5171509629"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "a13a665bffb238012b3ea254612e0b8690ab48ca9f0959e81878d5c5c62a90c6"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.i686-linux-gnu-cxx03.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75283180d6430fbee52fd668e9b5141069e76bec"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "ef309d2a5a775e122f03a7c8f004527e5b85836e5c1314a5a39d0b5985a56a5a"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.i686-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50c0957312d08fd1ef10a04e0a1b6271d610b22f"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "e469eb4fd56efbf149154ed905babc9a468dbc85cd6ea88b6763a4402b400ae2"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.i686-linux-musl-cxx03.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afc2786d7b2e5e2dc39b827a861da733c2287565"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "5ac1d8451fe05b5c8e891d8ae8e7584dbe918bc2f32416e1423b45ef0c4df992"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.i686-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b733af61d1b6cadd2fd3333c277af4b9553b2212"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "0889f6b665ce3ad3a14d8894ccef9c675caa407dc2a557d93c9bb2b5b15835de"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "497140605e5c530bb8ad9c4f9103dcc172309714"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "7548daa43553a37017ce1e89622a824e2c770df5229995b561379542c713c106"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[libsigcpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f5405d8559dda46c28800abbf982674ba4486db"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "3055ddc03b214f838bf298ce64b87c7179e2134e441a96addaf92442786aa906"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsigcpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca9edfcb00e50ba7c2cc46f45b4b5e892cf50880"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "60bdd7f1c2b9c540d3cdea6ad45afc8958fb8bcdcdc5c258a965ef106b7a35b5"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
git-tree-sha1 = "4dd8b73c93451f7a934d4c39913914b0ce0d6d96"
os = "macos"

    [[libsigcpp.download]]
    sha256 = "6096e61d0e4e1c0e172b148b443af3972024eb2b8f846c17bb0524fb32c800a9"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.x86_64-apple-darwin.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3cb7544f8bbe27178d379f0162da2992d1fe662c"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "519e5a6e7327aa7b059e98cb67de5fa84911968397d753676fc256a028932416"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b89a8cde8d64e0cbece3849c0b981765973b8a7a"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "012b1e446217e5ad697aec1d7d07b2d5c36ef9a1b5cb045ebf2203b23cbfe7ef"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bbf9de8e356955de45cf56016d26a86906df851"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "c4c7c9ddd2b4333c4e665a91a4c512980ee438fc74598f8da3f6c145e9608d43"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f3fd5dfbfc320abc94d9d90ad2e7474ae1635a0"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "f434f3d4aaad2acaa3e7f98e218ef5714305df3ec203b2fab166b793093a6298"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
git-tree-sha1 = "635db78ca95696d9895f4e23f4fd553d567c881d"
os = "freebsd"

    [[libsigcpp.download]]
    sha256 = "b7efe80a028cdcd779c31c39c44800736ccb50a084d0e3cb3e669d86e06fc4d2"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.x86_64-unknown-freebsd.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f55f10368b037340138aa5ba90f9495b38952036"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "4be9fb6c49675ed0d763db813203708ee944a32b27727c3196d93403ccf17fb1"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f3e0465b4b09d05014d2cfd7d63513365e54455"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "2f6acf2a00e17c889d6924af797a3442d5e83d78accf778d262cd209bc660fc9"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.4.0+0/libsigcpp.v3.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
