[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d28742ec2dbcf1d0f7750e6a392715c5482b0c2"
os = "macos"

    [[libsigcpp.download]]
    sha256 = "163b7cbd27df117ad03495dd487b71ac5a7540d65b7ca0794716ac64b9ae2537"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.aarch64-apple-darwin-cxx11.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82845b1f7b41e1a15b0223d13e9ed7ae65ff5ef5"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "e22df98de98495b8ebce6f0f00091371e6dcb979e5906d93a6acd1365f93b8df"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "befb16e826c9d650b506f0f2e04f33c92d7552db"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "19ecaaaa08d21ca2016c5364ed0ac99520038cdec5dc799e3f4cb391e15365c1"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1af3235d9f02b8826de02e417ee33a8b74f77f45"
os = "freebsd"

    [[libsigcpp.download]]
    sha256 = "843d4f46e86a57f8b4bca1f7a371403d34dbb357fdf4652710ee242bb5cc6272"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.aarch64-unknown-freebsd-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1f995f6d3e5a2b9bd965e101ec020551152dcaa"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "ea3c6bd4000ed8b5e95f28400185ac14360e473a83f2a80f2de977464fe2d88b"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2653ef5c3e9140cce2abb937910f50c571bc7ca6"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "a0be36f01c6aadb6fd98c67ab34e8b38622dcd55b67af418045837e2aeefa58c"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d871fb74deeeea75669e59417f4d2634bb339e30"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "954d4d77528efe0b25e900e3908175d4a42abe9ee60742fa4fc268830fa6f29f"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1dca8bb0575b9dccb07b43198ab5d3a61904194"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "bf9bfc1850f78a559bbb3c2bd26746a695f0ada195b3651bb57040913becaa53"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc7a3e25971f318dc738e627b7b36f2056d6fa8c"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "cee583ed74a598cf84b964577fb2a099db150fdfe53c176a3e91ad6cc7d3f475"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.i686-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fd07f8cdfa8bc4e2c1d01bb3f93fa25a4ed7ca7"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "cedd6e9313b4f1da3a5db22f63b54bd36c32925187e4287cb513941215359ba4"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.i686-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "586a466a93eb6e9682ecc1a4fd686d3ba8f89aa5"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "ce3c078f81ca4fd6cd345eff7f09fef3da9f1cd7274a233c725a339d4fdf0716"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[libsigcpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b7ca792e8b4df8f1b849e24cedda970eddac982"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "44c5951c7b1c26b7526b8c7f4996d3817cce796eb9f39865f9efda27becf1ee6"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "536dccd894aa3d72e4709648994d57883828355b"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "bce78b44c8fbffd099d3e060495378c53b3c824649718ea6048698e7c63d1fdf"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4be5cf6d64bd518e7950dffab825ea489b1ba11"
os = "macos"

    [[libsigcpp.download]]
    sha256 = "af66c0b9947afa506a0931c9279cdeb1d9599306a8af530157e5943888ae98c6"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.x86_64-apple-darwin-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e935a6d47a04bf913c4f6d1b52f0d92589f4d394"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "ce22b57fee2a4a9dff6f0c3816769878439f036e621e47448e857b5b49a8d2f9"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8294136acd13059715eb93d964964cbb3a4de4b6"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "1737db8bd762f517a102b9bfa851de82c2e67c2838b5a8e0a0814dd74dddde2b"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2afdd4c9cca8260d2bb2acd1ef2d4b994181dc49"
os = "freebsd"

    [[libsigcpp.download]]
    sha256 = "a2c19de8bb3e2789b86b874b6709299e369e291b11f90c9157ee74e16ffae531"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.x86_64-unknown-freebsd-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8684dc55ef10b778c17b981cae1710e97d8d308a"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "8d97e822a1073c977f960b4badbc70b85aa953fe850d8a8b6965c94137d4f62e"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v3.6.0+0/libsigcpp.v3.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
