[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d63b711654094ef1e9b99c06917ca4371e49bae0"
os = "macos"

    [[libsigcpp.download]]
    sha256 = "7260559f773b7c61d0fd30a2858bb1fb35e7d4e31d0305353a372d1c61b156e3"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.aarch64-apple-darwin-cxx03.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11d12e78f09ff73c9a594bc478fda42d2b478b4c"
os = "macos"

    [[libsigcpp.download]]
    sha256 = "654d5174fcae91fc7c8647454b16aa542673507e953c235ea1502502654c3dcf"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.aarch64-apple-darwin-cxx11.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "582333b31bbf7993c5a7bc1b9f412e6915a88a60"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "1caaec215c55d6d3361c1444f13f841f9e9a4961c0cca4770b6c936e60a087f0"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4eb9e9767da78a16bd461a9cb2bd5f8ef550d45"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "e471e1457923629498b7798757e00bd1541046881670db6b36bc9bebef0f4c3a"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdfba3f18a1f76bf6f33027d01001553b5710c32"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "1d06c6271d44e732bf1218d510650608315ca9978bd61c2e60ada48be50eb48c"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.aarch64-linux-musl-cxx03.tar.gz"
[[libsigcpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ea9e1cc617b88982e807ad4b4c80dac07feea46"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "dbb45a4610e37e9ec6df01cbdf59e091adc06c8210bbc48a3933ff56d74df0d4"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.aarch64-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abf3f9556da715d96831897bcfef8e2f87b46520"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "cb155fdcb43ad88a1b58d3ddf79bbfe924501e25a4961f116202034bbb72fc7d"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed6810653fe754516e70580b2e7cac4314411a13"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "c2ffd1febc68939677167b76635ebd6b705fbdd643f64e39d3754c623f2b35f4"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75c04ee6c651b5ca83c4dc119ac9d20a858825a9"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "fe0f9c0678176c04be19b22f58da4b45c905c5c7d1c77662def119efa596701b"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libsigcpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab1364767b6e97482c213f09d1da690099c805df"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "36c749ec6dd91a43fe4d7b03c76316df55ac35fdceb9a9498c494eb0916b566f"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77c353fc85d83211369e80104e1a6cd1d7fe9cf8"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "baf403dfa815f2018486e2a1d10cca154c8b3bc4895892df86db7080c3bee304"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7c12c288149297e816384c9b5633641198c3765"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "e3aa9849bf5a5b2b804442b449d36d8383f99274dcec055a15538fad1b17e7f5"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c305bb2497a6123ba84800d0e9b2377b2ea64d9"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "db9ec08939151c369163f2b39cf43f137fd9572b8ea462b490ad620732cb79b2"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsigcpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "556822d911934044ece9c732d2c2fff53de11d8b"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "95357db674204f70b206576ddc48a11afc8aa22e87f09acbe5b0470f32937419"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56212eee88a03657c6ca6744d6d92ce894f62896"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "e4fb55d9e7399be7df282a43490a487ec2462056f217830dffc3c92deaa5fc4d"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.i686-linux-gnu-cxx03.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a6215e64437832ce6d63037c5696cddc33e3a98"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "ad9d7e61b414252f1cbedbc45b2193666f0adc96fb9a101bf4a2fdcd8613eeea"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.i686-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6b0001cd7fa4feae60e760e195e54d65424a64b"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "6a3b5750257801046883d461b33e0f8d211b3649734ee46d168cb8221ad06a0b"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.i686-linux-musl-cxx03.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3984b4e73b7a2131f1daad7f3568f4f14ab630a"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "abdf5cd6188247ef5c923dc013a3c5eaa59f97250ca90ae7bc9f2df1d4880012"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.i686-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3625dcc353659bb45f4ea13034bd26826384bcbf"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "dad701f167f80c5e3eb582c389782a33ac3a2440ca8cbaaf0b743c3be497cfba"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.i686-w64-mingw32-cxx03.tar.gz"
[[libsigcpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9928b21913acf4a79bd816c8651aa906c6c55ff2"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "a5c34e5fd3656944367bda79b3e45a2ce5c0839e5d554f106f94114fb88570ca"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.i686-w64-mingw32-cxx11.tar.gz"
[[libsigcpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb68aaeb766870be259f4a64e7cab444620cf270"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "40c4dab2febee0fc7507efbd1290baec22321bd80bc0bc790535f88ec1fc5676"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsigcpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc7c5603bcf3acf8e637f17dbc56c415935e7431"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "f832c8e5518f6e61f61b308a6797471774ad26168ebe3af9f5cc7a2bee418b94"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79eb709441db8af666b54fc855ef4c2ff95edab1"
os = "macos"

    [[libsigcpp.download]]
    sha256 = "439f8648c5ef93eb08d0095d106666a1e0650f888458905653636fc442bc0b6e"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-apple-darwin-cxx03.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8fded050f74d6948cc7f63341bd34d3f5812f51"
os = "macos"

    [[libsigcpp.download]]
    sha256 = "d52a2e2f71124d96c8659a31a3d0bb975e92cf9b6d3d91b9cce65c0aa8f5b191"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-apple-darwin-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90a0ad082890f6807e133ed4311b5ce8edb70552"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "a1ed9465990f8b075c12a48298a085c1077acd3efca9f6e9fd3638267696a7f8"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58b8f28eebfba16ab71f70dd54454bfbca37bded"
libc = "glibc"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "82055e5846c9a2b6108704493bc92b7d2828fcf0f18296c038db7f59e42dd43e"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2300272d786eb5c2f25470e510cfe7d21a1540b8"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "e80b6fc4889500b2972b9c4433c5399c2004d07453ac4b32eaa9c967d71cd027"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-linux-musl-cxx03.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "959dba2719933956d384dd3971653fecf4d4a217"
libc = "musl"
os = "linux"

    [[libsigcpp.download]]
    sha256 = "76ea72787e9de8a11209634e0bd76e67f81686bc8ae7afea6aa4ec97059f6dd0"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-linux-musl-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "feebe35f7007563eefce0ccf80be1cb04a3c7f56"
os = "freebsd"

    [[libsigcpp.download]]
    sha256 = "0fdef6e95b61fe733e88118aad202b7cf003a15984a5532197ad54c4936ba8cf"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-unknown-freebsd-cxx03.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86bd795cd86124a1af2cd630e7d8593b9421e290"
os = "freebsd"

    [[libsigcpp.download]]
    sha256 = "6be278bb3d6ffb95276076efaf56248b6b9144f8857a4049ad7132b585e8e2fd"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-unknown-freebsd-cxx11.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20051c3097f7ab496211bb144299b6c6150745e1"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "3255522fb6cb889806c1e46fcd0a2e37425d9a99e64034742da67b6de4a7bc52"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libsigcpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be07cf7f9b3f9e22075c33552b86e1e773257939"
os = "windows"

    [[libsigcpp.download]]
    sha256 = "f6296e4161d7bc662c6c9de8951794b0f93dbff4573259ed79afd7b02c50ee8b"
    url = "https://github.com/JuliaBinaryWrappers/libsigcpp_jll.jl/releases/download/libsigcpp-v2.12.0+1/libsigcpp.v2.12.0.x86_64-w64-mingw32-cxx11.tar.gz"
